version: "3"
services:
  # backend:

  #   build: ./backend/b2c-server
  #   ports:
  #     - "3000:3000"
  #   env_file:
  #     - ./backend/b2c-server/.env

  frontend:
    build: ./frontend
    ports:
      - "3001:3001"
    env_file:
      - ./frontend/.env
