BASE_DIRECTORY=$(pwd)

FRONTEND_DIRECTORY="$BASE_DIRECTORY/frontend"
BACKEND_DIRECTORY="$BASE_DIRECTORY/backend"

BACKEND_HEROKU_APPNAME="pre-programming-api"
FRONTEND_HEROKU_APPNAME="pre-programming"