BASE_DIRECTORY="/Users/jeong-youseock/Desktop/pre-programming/"

DEPLOY_SHELL_DIRECTORY="$BASE_DIRECTORY/deploy"

FRONTEND_DIRECTORY="$BASE_DIRECTORY/frontend"
BACKEND_DIRECTORY="$BASE_DIRECTORY/backend"

BACKEND_HEROKU_APPNAME="pre-programming-api"
FRONTEND_HEROKU_APPNAME="pre-programming"